# PostgreSQL. Versions 8.2 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: me_development

test:
  <<: *default
  database: me_test

production:
  <<: *default
  database: me_production
  username: me
  password: <%= ENV['ME_DATABASE_PASSWORD'] %>
